USE [master]
GO

/****** Object:  Database [ccmsdb]    Script Date: 06/08/2013 11:54:45 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'ccmsdb')
DROP DATABASE [ccmsdb]
GO

USE [master]
GO

/****** Object:  Database [ccmsdb]    Script Date: 06/08/2013 11:54:45 ******/
CREATE DATABASE [ccmsdb] ON  PRIMARY 
( NAME = N'ccmsdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ccmsdb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ccmsdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ccmsdb_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ccmsdb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ccmsdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ccmsdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ccmsdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ccmsdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ccmsdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ccmsdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [ccmsdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ccmsdb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ccmsdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ccmsdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ccmsdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ccmsdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ccmsdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ccmsdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ccmsdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ccmsdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ccmsdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ccmsdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ccmsdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ccmsdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ccmsdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ccmsdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ccmsdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ccmsdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ccmsdb] SET  READ_WRITE 
GO

ALTER DATABASE [ccmsdb] SET RECOVERY FULL 
GO

ALTER DATABASE [ccmsdb] SET  MULTI_USER 
GO

ALTER DATABASE [ccmsdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ccmsdb] SET DB_CHAINING OFF 
GO


